# Generated by Django 5.2.3 on 2025-06-15 03:20

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "age",
                    models.IntegerField(validators=[accounts.validators.validate_age]),
                ),
                ("image", models.ImageField(upload_to="profile_pics/")),
            ],
        ),
    ]
